### ISSUE TITLE
How to build mods

### ISSUE THREAD

**Issue by anphetamina** [CTR-tools/CTR-ModSDK#134]
After following all the steps from [this](https://github.com/mateusfavarin/psx-modding-toolchain?tab=readme-ov-file#setup-1), I placed the `mod-builder` tool inside the `tools` folder.

When I run (the `build.bat` command is wrong):

```
python ..\..\..\tools\mod-builder\main.py
```

it complains about not finding the `settings.json`:

```
DEBUG:_files:CWD Parent(x0): D:\asant\Desktop\CTR-ModSDK\mods\Modules\EngineSelect
DEBUG:_files:CWD Parent(x1): D:\asant\Desktop\CTR-ModSDK\mods\Modules
DEBUG:_files:CWD Parent(x2): D:\asant\Desktop\CTR-ModSDK\mods
DEBUG:_files:CWD Parent(x3): D:\asant\Desktop\CTR-ModSDK
DEBUG:common:FOLDER_DISTANCE: D:\asant\Desktop\CTR-ModSDK
DEBUG:common:CWD: D:\asant\Desktop\CTR-ModSDK\mods\Modules\EngineSelect
DEBUG:common:GAME_NAME: mods
ERROR:root:[Errno 2] No such file or directory: 'D:\\asant\\Desktop\\settings.json'
Traceback (most recent call last):
  File "D:\asant\Desktop\CTR-ModSDK\tools\mod-builder\main.py", line 207, in <module>
    main = Main()
           ^^^^^^
  File "D:\asant\Desktop\CTR-ModSDK\tools\mod-builder\main.py", line 33, in __init__
    self.nops.load_config()
  File "D:\asant\Desktop\CTR-ModSDK\tools\mod-builder\nops.py", line 17, in load_config
    with open(SETTINGS_PATH) as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\asant\\Desktop\\settings.json'
```

So I tried placing the `EngineSelect` folder inside the `games/Example_CrashTeamRacing/mods` folder inside the `psx-modding-toolchain` cloned repository but when I run the `main.py` and try to build I get the following errors:

```
WARNING:compile_list:directory D:\asant\Desktop\psx-modding-toolchain\games\Example_CrashTeamRacing\Patches\EurLibcrypt\src not found at line: 2: 1020, exe, 0x80031cc8, 0x0, ../../Patches/EurLibcrypt/src/libcrypt.s

ERROR:compile_list:Undefined symbol: DecalHUD_Arrow2D at line: 16: common, exe, DecalHUD_Arrow2D, 0x0, ../../Patches/FixAdventureModeCharacterSelectArrows/src/DecalHUD_Arrow2D.c


WARNING:compile_list:directory D:\asant\Desktop\psx-modding-toolchain\games\Example_CrashTeamRacing\Patches\FixAdventureModeCharacterSelectArrows\src not found at line: 16: common, exe, DecalHUD_Arrow2D, 0x0, ../../Patches/FixAdventureModeCharacterSelectArrows/src/DecalHUD_Arrow2D.c

ERROR:compile_list:Undefined symbol: CS_Garage_GetMenuPtr at line: 26: common, 233, CS_Garage_GetMenuPtr, -0x8, src/ES_hook233.s


ERROR:compile_list:Undefined symbol: CS_EndOfFile at line: 27: common, 233, CS_EndOfFile, 0x0, src/ES_233.c


ERROR:compile_list:Undefined symbol: MM_TrackSelect_Video_SetDefaults at line: 37: common, 230, MM_TrackSelect_Video_SetDefaults, -0x8, src/ES_hook230.s


ERROR:compile_list:Undefined symbol: MM_EndOfFile at line: 38: common, 230, MM_EndOfFile, 0x0, src/ES_230.c
```

Any help?

**Comment by anphetamina** [comment]
The `EngineSelect` mod is broken
